Layout/LineLength:
  Enabled: false
Metrics:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoredMethods:
    - assert
    - paste
    - puts
    - raise
    - refute
    - require
    - send_keys
  IgnoredPatterns:
    - ^assert_
    - ^refute_
Style/NumericPredicate:
  AutoCorrect: true
  EnforcedStyle: comparison
Style/WordArray:
  MinSize: 1
