Layout/LineLength:
  Enabled: false
Metrics:
  Enabled: false
Lint/ShadowingOuterLocalVariable:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: false
  IgnoredMethods:
    - assert
    - attr_reader
    - exit
    - include
    - paste
    - puts
    - raise
    - refute
    - require
    - send_keys
  IgnoredPatterns:
    - ^assert_
    - ^refute_
Style/NumericPredicate:
  Enabled: false
Style/WordArray:
  MinSize: 1
